name: C/C++ CI

on:
  push:
    branches:
    - "**"
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update apt
      run: |
        sudo apt-get update
        apt-get install --yes ninja-build rsync zip
        apt-get install --yes pkg-config
        git clone https://github.com/Microsoft/vcpkg.git
        export VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT
        
    - name: cmake configure
      run: cmake --preset linux-release
    - name: build
      run: cmake --build --preset linux-release
