name: C/C++ CI

on:
  push:
    branches: "**"
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: gather dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes ninja-build rsync zip pkg-config libdbus-1-dev libxi-dev libxtst-dev libx11-dev libxrandr-dev libxcursor-dev libxdamage-dev libxinerama-dev nasm gperf bison  
        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
        
    - name: cmake configure
      run: cmake --preset linux-release
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
    - name: build
      run: cmake --build --preset linux-release
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
