name: C/C++ CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update apt
    - run: sudo apt-get update -y 
    - name: install ninja
      run: sudo apt-get install -y ninja-build
    - name: cmake configure
      run: cmake --preset linux-release
    - name: build
      run: cmake --build --preset linux-release
