name: C/C++ CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
   inputs:
    logLevel:
      description: 'Log level'
      required: false
      default: 'warning'
      type: choice
      options:
      - info
      - warning
      - debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update apt
      run: sudo apt-get update -y 
    - name: install ninja
      run: sudo apt-get install -y ninja-build
    - name: cmake configure
      run: cmake --preset linux-release
    - name: build
      run: cmake --build --preset linux-release
