name: C/C++ CI Windows

on:
  push:
    branches: "**"
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
jobs:
  build-release:
    runs-on: windows-latest
    steps:
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - uses: actions/checkout@v3
    - name: gather dependencies
      run: |
        choco install ninja
        echo "Cloning Vcpkg"
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.bat
        echo "Cloning done"

        chcp 65001 #set code page to utf-8
        echo ("VCPKG_ROOT=" + "./vcpkg") >> $env:GITHUB_ENV

    - name: cmake configure
      run:  cmake -DBUILD_APPS=ON -DBUILD_TESTS=ON --preset windows-release
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
    - name: build
      run: cmake --build --preset windows-release
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}

  build-debug:
    runs-on: windows-latest
    steps:
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - uses: actions/checkout@v3
    - name: gather dependencies
      run: |
        choco install ninja
        echo "Cloning Vcpkg"
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.bat
        echo "Cloning done"

        chcp 65001 #set code page to utf-8
        echo ("VCPKG_ROOT=" + "./vcpkg") >> $env:GITHUB_ENV

    - name: cmake configure
      run:  cmake -DBUILD_APPS=ON -DBUILD_TESTS=ON --preset windows-debug
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
    - name: build
      run: cmake --build --preset windows-debug
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}